version: '3.4'

services:
  postgre:
    image: postgres:14
    container_name: rad-db
    ports:
    - 5441:5432
    hostname: rad-db
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=123456
    volumes:
    - ../DockerVolumes/Db/.db/data:/var/lib/postgresql/data
