@startmindmap
<style>
mindmapDiagram {
    node {
        BackgroundColor white
    }
    :depth(1) {
      BackGroundColor #ffbbcc
    }
}
</style>

*[#Orange] Глобальные пробелы
**[#Green] Работа со списоком документов (групировки-сортировки-фильтры)
**[#LightGreen] Создание простой сущности (справочник) (поля ввода)
**[#Red]   Отображение больших деревьев (БР)

left side

**[#Red]   Редактирование "простого табличного документа" (ввод данных в грид)
**[#Red]   Редактирование древовидного документа
**[#Red]   Аналитические отчёты

**[#Red]   Отчеты

**[#Red]   Не забыть перейти на NgModule

@endmindmap