@startuml

actor "Пользователь" as usr
control "Прокси-балансировщик" as prx
entity signalR as sig
collections "Сервис получения данных" as rd
queue rabbit as q
participant "Сервис изменения данных" as wrk

== Получение данных ==
usr -> prx: Получение данных
prx -> rd: Получение данных
rd --> prx: <Результат>
prx --> usr: <Результат>

== ==
== Изменение данных ==
usr -> prx: Изменённые данные
prx -> rd: Изменённые данные
rd -> rd: Простановка "номера"\nизменения
rd -> q: Поставить в очередь 
q -> wrk: Обработка данных из очереди\nс валидацией БР и тд.
wrk -> q: Сообщение об внесении изменений\nИли сообщение об ошибке
q -> rd: <Обработка сообщения\n о внесении изменений>
rd -> sig: <Отсылка результата\nобработки запроса\nпользователю>
sig -> prx: <Отсылка результата\nобработки запроса\nпользователю>
prx -> usr: <Отсылка результата\nобработки запроса\nпользователю>

== ==


@enduml