// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rad.Db;

#nullable disable

namespace Rad.Database
{
    [DbContext(typeof(GrbsDbContext))]
    [Migration("20220905102602_DocInit")]
    partial class DocInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rad.Domain.Docs.Grbs.KuDetail.DocKuDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ApproveDt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("BrSid")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocStatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFirstDistribution")
                        .HasColumnType("boolean");

                    b.Property<long>("OrgSid")
                        .HasColumnType("bigint");

                    b.Property<long>("TopBrRowSid")
                        .HasColumnType("bigint");

                    b.Property<string>("TopFullSprKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserSid")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("KuDetails");
                });

            modelBuilder.Entity("Rad.Domain.Docs.Grbs.KuDetail.DocKuDetailRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ApproveDt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("BrSid")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocStatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFirstDistribution")
                        .HasColumnType("boolean");

                    b.Property<long>("OrgSid")
                        .HasColumnType("bigint");

                    b.Property<long>("TopBrRowSid")
                        .HasColumnType("bigint");

                    b.Property<string>("TopFullSprKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserSid")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("KuDetailRows");
                });

            modelBuilder.Entity("Rad.Domain.Docs.Grbs.ToPbs.DocToPbs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ApproveDt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("BrSid")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocStatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFirstDistribution")
                        .HasColumnType("boolean");

                    b.Property<long>("OrgSid")
                        .HasColumnType("bigint");

                    b.Property<long>("TopBrRowSid")
                        .HasColumnType("bigint");

                    b.Property<string>("TopFullSprKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserSid")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ToPbs");
                });

            modelBuilder.Entity("Rad.Domain.Docs.Grbs.ToPbs.DocToPbsRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ApproveDt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("BrSid")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocStatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFirstDistribution")
                        .HasColumnType("boolean");

                    b.Property<long>("OrgSid")
                        .HasColumnType("bigint");

                    b.Property<long>("TopBrRowSid")
                        .HasColumnType("bigint");

                    b.Property<string>("TopFullSprKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserSid")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ToPbsRows");
                });

            modelBuilder.Entity("Rad.Domain.Docs.Grbs.ToRezerv.DocToRezerv", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ApproveDt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("BrSid")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocStatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFirstDistribution")
                        .HasColumnType("boolean");

                    b.Property<long>("OrgSid")
                        .HasColumnType("bigint");

                    b.Property<long>("TopBrRowSid")
                        .HasColumnType("bigint");

                    b.Property<string>("TopFullSprKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserSid")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ToRezerv");
                });

            modelBuilder.Entity("Rad.Domain.Docs.Grbs.ToRezerv.DocToRezervRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ApproveDt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("BrSid")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocStatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFirstDistribution")
                        .HasColumnType("boolean");

                    b.Property<long>("OrgSid")
                        .HasColumnType("bigint");

                    b.Property<long>("TopBrRowSid")
                        .HasColumnType("bigint");

                    b.Property<string>("TopFullSprKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserSid")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ToRezervRows");
                });
#pragma warning restore 612, 618
        }
    }
}
