// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TestConsoleTest.Spr
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Загрузка справочников")]
    public partial class ЗагрузкаСправочниковFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("ru-RU"), "Spr", "Загрузка справочников", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Первичная загрузка данных НРПОФ 2016")]
        public void ПервичнаяЗагрузкаДанныхНРПОФ2016()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Первичная загрузка данных НРПОФ 2016", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                testRunner.Given("в справочнике \'НРПОФ\' количество записей = \'0\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                TechTalk.SpecFlow.Table table86 = new TechTalk.SpecFlow.Table(new string[] {
                            "Родитель",
                            "Код",
                            "Краткое наименование",
                            "Полное наименование",
                            "Является резервом",
                            "Начало",
                            "Конец"});
                table86.AddRow(new string[] {
                            "",
                            "10",
                            "Бюджет",
                            "Бюджет",
                            "N",
                            "01.01.2016",
                            "01.01.2100"});
                table86.AddRow(new string[] {
                            "10",
                            "11",
                            "Распределено по ПБС",
                            "Распределено по ПБС",
                            "N",
                            "01.01.2016",
                            "01.01.2100"});
                table86.AddRow(new string[] {
                            "10",
                            "12",
                            "Нераспределенный остаток",
                            "Нераспределенный остаток",
                            "Y",
                            "01.01.2016",
                            "01.01.2100"});
                table86.AddRow(new string[] {
                            "10",
                            "15",
                            "Списано",
                            "Списано",
                            "Y",
                            "01.01.2016",
                            "01.01.2100"});
                table86.AddRow(new string[] {
                            "10",
                            "13",
                            "Нераспределенный остаток за счет 5% превышения КУ",
                            "Нераспределенный остаток за счет 5% превышения КУ",
                            "Y",
                            "01.01.2016",
                            "01.01.2100"});
                table86.AddRow(new string[] {
                            "10",
                            "16",
                            "Списано превышенных ПОФ",
                            "Списано превышенных ПОФ",
                            "Y",
                            "01.01.2016",
                            "01.01.2100"});
                table86.AddRow(new string[] {
                            "",
                            "20",
                            "ДИБФ",
                            "ДИБФ",
                            "N",
                            "01.01.2016",
                            "01.01.2100"});
                table86.AddRow(new string[] {
                            "20",
                            "21",
                            "Распределено по ПБС",
                            "Распределено по ПБС",
                            "N",
                            "01.01.2016",
                            "01.01.2100"});
                table86.AddRow(new string[] {
                            "20",
                            "22",
                            "Нераспределенный остаток",
                            "Нераспределенный остаток",
                            "Y",
                            "01.01.2016",
                            "01.01.2100"});
                table86.AddRow(new string[] {
                            "20",
                            "25",
                            "Списано",
                            "Списано",
                            "Y",
                            "01.01.2016",
                            "01.01.2100"});
                table86.AddRow(new string[] {
                            "20",
                            "23",
                            "Нераспределенный остаток за счет 5% превышения КУ",
                            "Нераспределенный остаток за счет 5% превышения КУ",
                            "Y",
                            "01.01.2016",
                            "01.01.2100"});
                table86.AddRow(new string[] {
                            "20",
                            "26",
                            "Списано превышенных ПОФ",
                            "Списано превышенных ПОФ",
                            "Y",
                            "01.01.2016",
                            "01.01.2100"});
                testRunner.When("вводим в справочник \'НРПОФ\' запись:", ((string)(null)), table86, "Когда ");
                testRunner.Then("всё хорошо", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
