// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TestConsoleTest.Spr
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Ввод справочника НР")]
    public partial class ВводСправочникаНРFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("ru-RU"), "Spr", "Ввод справочника НР", "Заполнение справочника НР", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Первичная загрузка данных НР")]
        [NUnit.Framework.CategoryAttribute("регрес")]
        public void ПервичнаяЗагрузкаДанныхНР()
        {
            string[] tagsOfScenario = new string[] {
                    "регрес"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Первичная загрузка данных НР", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                testRunner.Given("в справочнике \'НР\' количество записей = \'0\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                TechTalk.SpecFlow.Table table93 = new TechTalk.SpecFlow.Table(new string[] {
                            "Родитель",
                            "Код",
                            "Является резервом",
                            "Полное наименование",
                            "Краткое наименование",
                            "Начало",
                            "Конец"});
                table93.AddRow(new string[] {
                            "",
                            "0000",
                            "Да",
                            "Нераспределенные остатки",
                            "Нераспределенные остатки",
                            "01.01.1900",
                            "01.01.2100"});
                table93.AddRow(new string[] {
                            "",
                            "0001",
                            "Нет",
                            "Обеспечивающие Управления",
                            "Обеспечивающие Управления",
                            "01.01.1900",
                            "01.01.2100"});
                table93.AddRow(new string[] {
                            "",
                            "0101",
                            "Нет",
                            "Обслуживание официальных лиц",
                            "Обслуживание официальных лиц",
                            "01.01.1900",
                            "01.01.2100"});
                table93.AddRow(new string[] {
                            "",
                            "1601",
                            "Нет",
                            "Выплаты пенсионерам",
                            "Выплаты пенсионерам",
                            "01.01.1900",
                            "01.01.2100"});
                table93.AddRow(new string[] {
                            "",
                            "1602",
                            "Нет",
                            "Прочие",
                            "Прочие",
                            "01.01.1900",
                            "01.01.2100"});
                table93.AddRow(new string[] {
                            "",
                            "1603",
                            "Нет",
                            "Сопровождение ПО и СЭД",
                            "Сопровождение ПО и СЭД",
                            "01.01.1900",
                            "01.01.2100"});
                table93.AddRow(new string[] {
                            "",
                            "1604",
                            "Нет",
                            "Внедрение АСУ БС ФСИН России",
                            "Внедрение АСУ БС ФСИН России",
                            "01.01.1900",
                            "01.01.2100"});
                table93.AddRow(new string[] {
                            "",
                            "1609",
                            "Нет",
                            "Проезд в отпуск (Крайний Север)",
                            "Проезд в отпуск (Крайний Север)",
                            "01.01.1900",
                            "01.01.2100"});
                table93.AddRow(new string[] {
                            "",
                            "1611",
                            "Нет",
                            "Металлолом",
                            "Металлолом",
                            "01.01.1900",
                            "01.01.2100"});
                table93.AddRow(new string[] {
                            "",
                            "2002",
                            "Нет",
                            "Содержание энергохозяйства",
                            "Содержание энергохозяйства",
                            "01.01.1900",
                            "01.01.2100"});
                table93.AddRow(new string[] {
                            "",
                            "2101",
                            "Нет",
                            "Продовольственное обеспечение",
                            "Продовольственное обеспечение",
                            "01.01.1900",
                            "01.01.2100"});
                table93.AddRow(new string[] {
                            "",
                            "2102",
                            "Нет",
                            "Вещевое обеспечение",
                            "Вещевое обеспечение",
                            "01.01.1900",
                            "01.01.2100"});
                table93.AddRow(new string[] {
                            "",
                            "2103",
                            "Нет",
                            "Котельно-печное топливо",
                            "Котельно-печное топливо",
                            "01.01.1900",
                            "01.01.2100"});
                table93.AddRow(new string[] {
                            "",
                            "2113",
                            "Нет",
                            "Автобронетехника и ГСМ",
                            "Автобронетехника и ГСМ",
                            "01.01.1900",
                            "01.01.2100"});
                table93.AddRow(new string[] {
                            "",
                            "2114",
                            "Нет",
                            "Перевозка личного состава (ОГ)",
                            "Перевозка личного состава (ОГ)",
                            "01.01.1900",
                            "01.01.2100"});
                table93.AddRow(new string[] {
                            "",
                            "2503",
                            "Нет",
                            "Аттестация объектов",
                            "Аттестация объектов",
                            "01.01.1900",
                            "01.01.2100"});
                table93.AddRow(new string[] {
                            "",
                            "2801",
                            "Нет",
                            "Текущие командировки",
                            "Текущие командировки",
                            "01.01.1900",
                            "01.01.2100"});
                table93.AddRow(new string[] {
                            "",
                            "2802",
                            "Нет",
                            "Переподготовка (УК)",
                            "Переподготовка (УК)",
                            "01.01.1900",
                            "01.01.2100"});
                table93.AddRow(new string[] {
                            "",
                            "2803",
                            "Нет",
                            "Ревизии",
                            "Ревизии",
                            "01.01.1900",
                            "01.01.2100"});
                table93.AddRow(new string[] {
                            "",
                            "2804",
                            "Нет",
                            "Экстрадиция",
                            "Экстрадиция",
                            "01.01.1900",
                            "01.01.2100"});
                table93.AddRow(new string[] {
                            "",
                            "2805",
                            "Нет",
                            "ОГ ФСИН России",
                            "ОГ ФСИН России",
                            "01.01.1900",
                            "01.01.2100"});
                table93.AddRow(new string[] {
                            "",
                            "2806",
                            "Нет",
                            "Конвоирование",
                            "Конвоирование",
                            "01.01.1900",
                            "01.01.2100"});
                table93.AddRow(new string[] {
                            "",
                            "2809",
                            "Нет",
                            "Практика курсантов",
                            "Практика курсантов",
                            "01.01.1900",
                            "01.01.2100"});
                table93.AddRow(new string[] {
                            "",
                            "3201",
                            "Нет",
                            "ФКУ ЦИТО ФСИН России",
                            "ФКУ ЦИТО ФСИН России",
                            "01.01.1900",
                            "01.01.2100"});
                testRunner.When("вводим в справочник \'НР\' запись:", ((string)(null)), table93, "Когда ");
                testRunner.Then("в справочнике \'НР\' количество записей = \'24\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Первичная загрузка данных НР (2015)")]
        public void ПервичнаяЗагрузкаДанныхНР2015()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Первичная загрузка данных НР (2015)", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                testRunner.Given("в справочнике \'НР\' количество записей = \'0\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                TechTalk.SpecFlow.Table table94 = new TechTalk.SpecFlow.Table(new string[] {
                            "Родитель",
                            "Код",
                            "Является резервом",
                            "Полное наименование",
                            "Краткое наименование",
                            "Начало",
                            "Конец"});
                table94.AddRow(new string[] {
                            "",
                            "01--",
                            "Да",
                            "(финансирование)",
                            "(финансирование)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0101",
                            "Да",
                            "Распределено по ПБС",
                            "Распределено по ПБС",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0102",
                            "Да",
                            "Нераспределенный остаток",
                            "Нераспределенный остаток",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0103",
                            "Да",
                            "Блокировка",
                            "Блокировка",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0104",
                            "Да",
                            "Обслуживание официальных лиц (Резерв)",
                            "Обслуживание официальных лиц (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0105",
                            "Да",
                            "Обслуживание официальных лиц (ПБС)",
                            "Обслуживание официальных лиц (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0106",
                            "Да",
                            "Подписка (Резерв)",
                            "Подписка (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0107",
                            "Да",
                            "Подписка (ПБС)",
                            "Подписка (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0108",
                            "Да",
                            "Международное сотрудничество (Резерв)",
                            "Международное сотрудничество (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0109",
                            "Да",
                            "Международное сотрудничество (ПБС)",
                            "Международное сотрудничество (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "02--",
                            "Да",
                            "(финансирование)",
                            "(финансирование)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0201",
                            "Да",
                            "Блокировка",
                            "Блокировка",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0202",
                            "Да",
                            "Распределено по ПБС",
                            "Распределено по ПБС",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0203",
                            "Да",
                            "Нераспределенный остаток",
                            "Нераспределенный остаток",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "03--",
                            "Да",
                            "(финансирование)",
                            "(финансирование)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0301",
                            "Да",
                            "Блокировка",
                            "Блокировка",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0302",
                            "Да",
                            "Распределено по ПБС",
                            "Распределено по ПБС",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0303",
                            "Да",
                            "Нераспределенный остаток",
                            "Нераспределенный остаток",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0304",
                            "Да",
                            "Спортивные мероприятия (Резерв)",
                            "Спортивные мероприятия (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0305",
                            "Да",
                            "Спортивные мероприятия (ПБС)",
                            "Спортивные мероприятия (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0306",
                            "Да",
                            "Изготовление удостоверений (Резерв)",
                            "Изготовление удостоверений (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0307",
                            "Да",
                            "Изготовление удостоверений (ПБС)",
                            "Изготовление удостоверений (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0308",
                            "Да",
                            "Стипендии Президента (Резерв)",
                            "Стипендии Президента (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0309",
                            "Да",
                            "Стипендии Президента (ПБС)",
                            "Стипендии Президента (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0310",
                            "Да",
                            "Стипендии Правительства (Резерв)",
                            "Стипендии Правительства (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0311",
                            "Да",
                            "Стипендии Правительства (ПБС)",
                            "Стипендии Правительства (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0312",
                            "Да",
                            "Стипендии Державина (Резерв)",
                            "Стипендии Державина (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0313",
                            "Да",
                            "Стипендии Державина (ПБС)",
                            "Стипендии Державина (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0314",
                            "Да",
                            "Именные стипендии (Резерв)",
                            "Именные стипендии (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0315",
                            "Да",
                            "Именные стипендии  (ПБС)",
                            "Именные стипендии  (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "04--",
                            "Да",
                            "(финансирование)",
                            "(финансирование)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0401",
                            "Да",
                            "Блокировка",
                            "Блокировка",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0402",
                            "Да",
                            "Распределено по ПБС",
                            "Распределено по ПБС",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0403",
                            "Да",
                            "Нераспределенный остаток",
                            "Нераспределенный остаток",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "05--",
                            "Да",
                            "(финансирование)",
                            "(финансирование)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0501",
                            "Да",
                            "Блокировка",
                            "Блокировка",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0502",
                            "Да",
                            "Распределено по ПБС",
                            "Распределено по ПБС",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0503",
                            "Да",
                            "Нераспределенный остаток",
                            "Нераспределенный остаток",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "06--",
                            "Да",
                            "(финансирование)",
                            "(финансирование)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0601",
                            "Да",
                            "Блокировка",
                            "Блокировка",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0602",
                            "Да",
                            "Распределено по ПБС",
                            "Распределено по ПБС",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0603",
                            "Да",
                            "Нераспределенный остаток",
                            "Нераспределенный остаток",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "07--",
                            "Да",
                            "(финансирование)",
                            "(финансирование)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0701",
                            "Да",
                            "Блокировка",
                            "Блокировка",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0702",
                            "Да",
                            "Распределено по ПБС",
                            "Распределено по ПБС",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0703",
                            "Да",
                            "Нераспределенный остаток",
                            "Нераспределенный остаток",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "08--",
                            "Да",
                            "(финансирование)",
                            "(финансирование)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0801",
                            "Да",
                            "Блокировка",
                            "Блокировка",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0802",
                            "Да",
                            "Распределено по ПБС",
                            "Распределено по ПБС",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0803",
                            "Да",
                            "Нераспределенный остаток",
                            "Нераспределенный остаток",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0804",
                            "Да",
                            "Металлолом (Резерв)",
                            "Металлолом (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0805",
                            "Да",
                            "Металлолом (ПБС)",
                            "Металлолом (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0806",
                            "Да",
                            "Субсидии (Резерв)",
                            "Субсидии (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0807",
                            "Да",
                            "Субсидии (ПБС)",
                            "Субсидии (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "09--",
                            "Да",
                            "(финансирование)",
                            "(финансирование)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0901",
                            "Да",
                            "Блокировка",
                            "Блокировка",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0902",
                            "Да",
                            "Распределено по ПБС",
                            "Распределено по ПБС",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0903",
                            "Да",
                            "Нераспределенный остаток",
                            "Нераспределенный остаток",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0904",
                            "Да",
                            "Содержание энергохозяйства (Резерв)",
                            "Содержание энергохозяйства (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0905",
                            "Да",
                            "Содержание энергохозяйства (ПБС)",
                            "Содержание энергохозяйства (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0906",
                            "Да",
                            "Котельно-печное топливо (Резерв)",
                            "Котельно-печное топливо (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0907",
                            "Да",
                            "Котельно-печное топливо (ПБС)",
                            "Котельно-печное топливо (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0908",
                            "Да",
                            "Текущий ремонт (Резерв)",
                            "Текущий ремонт (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "0909",
                            "Да",
                            "Текущий ремонт (ПБС)",
                            "Текущий ремонт (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "10--",
                            "Да",
                            "(финансирование)",
                            "(финансирование)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1001",
                            "Да",
                            "Блокировка",
                            "Блокировка",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1002",
                            "Да",
                            "Распределено по ПБС",
                            "Распределено по ПБС",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1003",
                            "Да",
                            "Нераспределенный остаток",
                            "Нераспределенный остаток",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1004",
                            "Да",
                            "Продовольственное обеспечение (Резерв)",
                            "Продовольственное обеспечение (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1005",
                            "Да",
                            "Продовольственное обеспечение (ПБС)",
                            "Продовольственное обеспечение (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1006",
                            "Да",
                            "Вещевое обеспечение (Резерв)",
                            "Вещевое обеспечение (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1007",
                            "Да",
                            "Вещевое обеспечение (ПБС)",
                            "Вещевое обеспечение (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1008",
                            "Да",
                            "Банно-прачечное обеспечение (Резерв)",
                            "Банно-прачечное обеспечение (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1009",
                            "Да",
                            "Банно-прачечное обеспечение (ПБС)",
                            "Банно-прачечное обеспечение (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1010",
                            "Да",
                            "Средства личной гигиены (Резерв)",
                            "Средства личной гигиены (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1011",
                            "Да",
                            "Средства личной гигиены (ПБС)",
                            "Средства личной гигиены (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1012",
                            "Да",
                            "Автобронетехника и ГСМ (Резерв)",
                            "Автобронетехника и ГСМ (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1013",
                            "Да",
                            "Автобронетехника и ГСМ (ПБС)",
                            "Автобронетехника и ГСМ (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1014",
                            "Да",
                            "Перевозка личного состава (Резерв)",
                            "Перевозка личного состава (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1015",
                            "Да",
                            "Перевозка личного состава (ПБС)",
                            "Перевозка личного состава (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1016",
                            "Да",
                            "Обеспечение спецназа (Резерв)",
                            "Обеспечение спецназа (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1017",
                            "Да",
                            "Обеспечение спецназа (ПБС)",
                            "Обеспечение спецназа (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "11--",
                            "Да",
                            "(финансирование)",
                            "(финансирование)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1101",
                            "Да",
                            "Блокировка",
                            "Блокировка",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1102",
                            "Да",
                            "Распределено по ПБС",
                            "Распределено по ПБС",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1103",
                            "Да",
                            "Нераспределенный остаток",
                            "Нераспределенный остаток",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "12--",
                            "Да",
                            "(финансирование)",
                            "(финансирование)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1201",
                            "Да",
                            "Блокировка",
                            "Блокировка",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1202",
                            "Да",
                            "Распределено по ПБС",
                            "Распределено по ПБС",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1203",
                            "Да",
                            "Нераспределенный остаток",
                            "Нераспределенный остаток",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "13--",
                            "Да",
                            "(финансирование)",
                            "(финансирование)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1301",
                            "Да",
                            "Блокировка",
                            "Блокировка",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1302",
                            "Да",
                            "Распределено по ПБС",
                            "Распределено по ПБС",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1303",
                            "Да",
                            "Нераспределенный остаток",
                            "Нераспределенный остаток",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "14--",
                            "Да",
                            "(финансирование)",
                            "(финансирование)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1401",
                            "Да",
                            "Блокировка",
                            "Блокировка",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1402",
                            "Да",
                            "Распределено по ПБС",
                            "Распределено по ПБС",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1403",
                            "Да",
                            "Нераспределенный остаток",
                            "Нераспределенный остаток",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1404",
                            "Да",
                            "Аттестация объектов (Резерв)",
                            "Аттестация объектов (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1405",
                            "Да",
                            "Аттестация объектов (ПБС)",
                            "Аттестация объектов (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1406",
                            "Да",
                            "Услуги связи (Резерв)",
                            "Услуги связи (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1407",
                            "Да",
                            "Услуги связи (ПБС)",
                            "Услуги связи (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1408",
                            "Да",
                            "Пожарная безопасность (Резерв)",
                            "Пожарная безопасность (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1409",
                            "Да",
                            "Пожарная безопасность (ПБС)",
                            "Пожарная безопасность (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1410",
                            "Да",
                            "СЭМПЛ (Резерв)",
                            "СЭМПЛ (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1411",
                            "Да",
                            "СЭМПЛ (ПБС)",
                            "СЭМПЛ (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1412",
                            "Да",
                            "Оборудование ИТСОН (Резерв)",
                            "Оборудование ИТСОН (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1413",
                            "Да",
                            "Оборудование ИТСОН (ПБС)",
                            "Оборудование ИТСОН (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "15--",
                            "Да",
                            "(финансирование)",
                            "(финансирование)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1501",
                            "Да",
                            "Блокировка",
                            "Блокировка",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1502",
                            "Да",
                            "Распределено по ПБС",
                            "Распределено по ПБС",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1503",
                            "Да",
                            "Нераспределенный остаток",
                            "Нераспределенный остаток",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "16--",
                            "Да",
                            "(финансирование)",
                            "(финансирование)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1601",
                            "Да",
                            "Блокировка",
                            "Блокировка",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1602",
                            "Да",
                            "Распределено по ПБС",
                            "Распределено по ПБС",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1603",
                            "Да",
                            "Нераспределенный остаток",
                            "Нераспределенный остаток",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "17--",
                            "Да",
                            "(финансирование)",
                            "(финансирование)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1701",
                            "Да",
                            "Блокировка",
                            "Блокировка",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1702",
                            "Да",
                            "Текущие командировки (Резерв)",
                            "Текущие командировки (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1703",
                            "Да",
                            "Текущие командировки (ПБС)",
                            "Текущие командировки (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1704",
                            "Да",
                            "Переподготовка кадров (Резерв)",
                            "Переподготовка кадров (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1705",
                            "Да",
                            "Переподготовка кадров (ПБС)",
                            "Переподготовка кадров (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1706",
                            "Да",
                            "Ревизии (Резерв)",
                            "Ревизии (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1707",
                            "Да",
                            "Ревизии (ПБС)",
                            "Ревизии (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1708",
                            "Да",
                            "Экстрадиция (Резерв)",
                            "Экстрадиция (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1709",
                            "Да",
                            "Экстрадиция (ПБС)",
                            "Экстрадиция (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1711",
                            "Да",
                            "ОГ ФСИН России (Резерв)",
                            "ОГ ФСИН России (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1712",
                            "Да",
                            "ОГ ФСИН России (ПБС)",
                            "ОГ ФСИН России (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1713",
                            "Да",
                            "Конвоирование (Резерв)",
                            "Конвоирование (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1714",
                            "Да",
                            "Конвоирование (ПБС)",
                            "Конвоирование (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1715",
                            "Да",
                            "Усиление (Резерв)",
                            "Усиление (Резерв)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1716",
                            "Да",
                            "Усиление (ПБС)",
                            "Усиление (ПБС)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "18--",
                            "Да",
                            "(финансирование)",
                            "(финансирование)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1801",
                            "Да",
                            "Блокировка",
                            "Блокировка",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1802",
                            "Да",
                            "Распределено по ПБС",
                            "Распределено по ПБС",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1803",
                            "Да",
                            "Нераспределенный остаток",
                            "Нераспределенный остаток",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "19--",
                            "Да",
                            "(финансирование)",
                            "(финансирование)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1901",
                            "Да",
                            "Распределено по ПБС",
                            "Распределено по ПБС",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "1902",
                            "Да",
                            "Нераспределенный остаток",
                            "Нераспределенный остаток",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "20--",
                            "Да",
                            "(финансирование)",
                            "(финансирование)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "2001",
                            "Да",
                            "Распределено по ПБС",
                            "Распределено по ПБС",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "2002",
                            "Да",
                            "Нераспределенный остаток",
                            "Нераспределенный остаток",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "21--",
                            "Да",
                            "(финансирование)",
                            "(финансирование)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "2101",
                            "Да",
                            "Блокировка",
                            "Блокировка",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "2102",
                            "Да",
                            "Нераспределенный остаток",
                            "Нераспределенный остаток",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "22--",
                            "Да",
                            "(финансирование)",
                            "(финансирование)",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "2201",
                            "Да",
                            "Блокировка",
                            "Блокировка",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "2202",
                            "Да",
                            "Нераспределенный остаток",
                            "Нераспределенный остаток",
                            "01.01.1900",
                            "01.01.2100"});
                table94.AddRow(new string[] {
                            "",
                            "23--",
                            "Да",
                            "(финансирование)",
                            "(финансирование)",
                            "01.01.1900",
                            "01.01.2100"});
                testRunner.When("вводим в справочник \'НР\' запись:", ((string)(null)), table94, "Когда ");
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
