// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TestConsoleTest.Spr
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Ввод справочника Округа")]
    public partial class ВводСправочникаОкругаFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("ru-RU"), "Spr", "Ввод справочника Округа", "Заполнение справочника Округа", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Первичная загрузка данных Округа")]
        [NUnit.Framework.CategoryAttribute("регрес")]
        public void ПервичнаяЗагрузкаДанныхОкруга()
        {
            string[] tagsOfScenario = new string[] {
                    "регрес"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Первичная загрузка данных Округа", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                testRunner.Given("в справочнике \'Округа\' количество записей = \'0\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                TechTalk.SpecFlow.Table table100 = new TechTalk.SpecFlow.Table(new string[] {
                            "Родитель",
                            "Код",
                            "Полное наименование",
                            "Краткое наименование",
                            "Начало",
                            "Конец"});
                table100.AddRow(new string[] {
                            "",
                            "01",
                            "Центральный",
                            "Центральный",
                            "01.01.1900",
                            "01.01.2100"});
                table100.AddRow(new string[] {
                            "",
                            "02",
                            "Северо-Западный",
                            "Северо-Западный",
                            "01.01.1900",
                            "01.01.2100"});
                table100.AddRow(new string[] {
                            "",
                            "03",
                            "Южный",
                            "Южный",
                            "01.01.1900",
                            "01.01.2100"});
                table100.AddRow(new string[] {
                            "",
                            "04",
                            "Приволжский",
                            "Приволжский",
                            "01.01.1900",
                            "01.01.2100"});
                table100.AddRow(new string[] {
                            "",
                            "05",
                            "Уральский",
                            "Уральский",
                            "01.01.1900",
                            "01.01.2100"});
                table100.AddRow(new string[] {
                            "",
                            "06",
                            "Сибирский",
                            "Сибирский",
                            "01.01.1900",
                            "01.01.2100"});
                table100.AddRow(new string[] {
                            "",
                            "07",
                            "Дальневосточный",
                            "Дальневосточный",
                            "01.01.1900",
                            "01.01.2100"});
                table100.AddRow(new string[] {
                            "",
                            "08",
                            "Северо-Кавказский",
                            "Северо-Кавказский",
                            "01.01.1900",
                            "01.01.2100"});
                table100.AddRow(new string[] {
                            "",
                            "09",
                            "Крымский",
                            "Крымский",
                            "01.01.1900",
                            "01.01.2100"});
                testRunner.When("вводим в справочник \'Округа\' запись:", ((string)(null)), table100, "Когда ");
                testRunner.Then("в справочнике \'Округа\' количество записей = \'9\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
